# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SUMMER20)', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], help_text='Type of discount', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., 10.00 for $10 or 0.10 for 10%)', max_digits=8)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_usage', models.IntegerField(blank=True, help_text='Maximum number of times this coupon can be used overall', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('stackable', models.BooleanField(default=False, help_text='Can be combined with other discounts')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount for coupon to apply', max_digits=12, null=True)),
                ('user_restriction', models.JSONField(blank=True, default=list, help_text='JSON array of user UUIDs or criteria for restriction', null=True)),
                ('country_restriction', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, help_text='List of ISO 3166-1 country codes', null=True, size=None)),
                ('category_restriction', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='List of Category UUIDs', null=True, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'indexes': [models.Index(fields=['code'], name='discounts_c_code_3b6115_idx'), models.Index(fields=['start_date', 'end_date'], name='discounts_c_start_d_bf7c31_idx'), models.Index(fields=['type'], name='discounts_c_type_53b3b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('auto', 'Automatic'), ('code', 'Requires Code')], help_text='How the discount is applied', max_length=10)),
                ('scope', models.CharField(choices=[('product', 'Product'), ('cart', 'Cart'), ('category', 'Category')], max_length=10)),
                ('conditions', models.JSONField(default=dict, help_text='JSON defining conditions (e.g., {"min_quantity": 3, "product_ids": []})')),
                ('effect', models.JSONField(default=dict, help_text='JSON defining effect (e.g., {"discount_type": "percent", "value": 15})')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'discount rule',
                'verbose_name_plural': 'discount rules',
                'indexes': [models.Index(fields=['name'], name='discounts_d_name_743544_idx'), models.Index(fields=['type', 'scope', 'is_active'], name='discounts_d_type_23af58_idx'), models.Index(fields=['start_date', 'end_date'], name='discounts_d_start_d_e73fc6_idx')],
            },
        ),
    ]
