# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text='Link to a registered user if guest converts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_guest'], name='customers_c_is_gues_31d525_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['linked_user'], name='customers_c_linked__3ef2cd_idx'),
        ),
    ]
