# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text='e.g., "User", "Product", "Order"', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, help_text='UUID of the affected entity', null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('refund', 'Refund'), ('ship', 'Ship')], max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='JSON of old field values before update/delete', null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='JSON of new field values after create/update', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_endpoint', models.CharField(blank=True, help_text='API endpoint accessed', max_length=255, null=True)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
            },
        ),
    ]
