# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignments', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='rbac_role_name_92eec1_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system_role'], name='rbac_role_is_syst_76b3e7_idx'),
        ),
        migrations.AddField(
            model_name='policyassignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignments', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role'),
        ),
        migrations.AddIndex(
            model_name='securitypolicy',
            index=models.Index(fields=['policy_type', 'applies_to'], name='rbac_securi_policy__174197_idx'),
        ),
        migrations.AddField(
            model_name='policyassignment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rbac.securitypolicy'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_users', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to='users.user'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='rbac_rolepe_role_id_4acee1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='policyassignment',
            index=models.Index(fields=['policy', 'role'], name='rbac_policy_policy__d007c3_idx'),
        ),
        migrations.AddIndex(
            model_name='policyassignment',
            index=models.Index(fields=['policy', 'user'], name='rbac_policy_policy__b2c24c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyassignment',
            unique_together={('policy', 'role'), ('policy', 'user')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission'], name='rbac_userpe_user_id_ba28fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['grant_type'], name='rbac_userpe_grant_t_2c13af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='rbac_userro_user_id_f47914_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='rbac_userro_expires_4bffce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'scope_id')},
        ),
    ]
