# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked to a customer (can be guest or registered)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='customers.customer'),
        ),
    ]
