# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Linked to a registered user profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.profile'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['profile', 'status'], name='cart_cart_profile_965989_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer', 'status'], name='cart_cart_custome_17ff89_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='cart_cart_expires_8a239f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='cart_cart_created_981ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product_variant'], name='cart_cartit_cart_id_52ca2b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='cart_cartit_added_a_c3b0c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_variant')},
        ),
    ]
