# Generated by Django 5.2.3 on 2025-06-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to='users.user'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='products.product'),
        ),
        migrations.AddField(
            model_name='productcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='products.collection'),
        ),
        migrations.AddField(
            model_name='productcollection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='products.product'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='products.product'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='products_ta_slug_d1be68_idx'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_products', to='products.tag'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'available_from', 'available_to'], name='products_pr_status_e5f9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_price'], name='products_pr_base_pr_658bee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['global_trade_id'], name='products_pr_global__027389_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['product', 'category'], name='products_pr_product_edf63f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
        migrations.AddIndex(
            model_name='productcollection',
            index=models.Index(fields=['product', 'collection'], name='products_pr_product_9a32da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcollection',
            unique_together={('product', 'collection')},
        ),
        migrations.AddIndex(
            model_name='producttranslation',
            index=models.Index(fields=['language', 'name'], name='products_pr_languag_0532cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'sku'], name='products_pr_product_b3af96_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['inventory_quantity'], name='products_pr_invento_8d9599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'attributes')},
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['product', 'tag'], name='products_pr_product_ac26b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('product', 'tag')},
        ),
    ]
